server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

rocketmq:
  name-server: 47.98.209.26:9876
  producer:
    group: Netty-group
    sendMessageTimeout: 300000
